### ISSUE TITLE
Not able to get the location of mouse click to insert image same as Shape addin works

### ISSUE THREAD

**Issue by goyalprashant96** [OfficeDev/Office-Addin-TaskPane#70]

**Comment by arttarawork** [comment]
Hi, if this is still an issue, can you please send more information?

Stack traces, screenshots, version infos all help.

**Comment by goyalprashant96** [comment]
> Hi, if this is still an issue, can you please send more information?
> 
> Stack traces, screenshots, version infos all help.

@arttarawork  Yes, the issue is while inserting image on left mouse click. I would like to select image and insert on mouse click anywhere in the document but it is alwaya get inserted where the pointer can be (like if I have writen 2 lines then I am able to insert but when try to insert at bottom of page lets say then it will always get inserted at the end of first 2 lines )

So, I am just gettign the location of pointer where one can write text but not the location where i clicked.

**Comment by TCourtneyOwen** [comment]
Is this an issue related to the Office-Addin-Taskpane project template? From the issue description it's not clear to me that it is - perhaps the problem is with the office-js you are using? If you are trying to get the location of the mouse click programmatically through Office-Js, can you please include the code snippet and we will see if we can get someone from the Office-Js team look into this.

Thanks,

Courtney
